config/routes.rb
Rails.application.routes.draw do
  resources :feeds do
    collection do
      post :confirm
    end
  end
  # resources :feeds
  root to: 'homes#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :posts
  get '/confirmed/:id', to: 'posts#confirmed', as: 'confirmed'
  get '/confirm/:id', to: 'posts#confirm', as: 'confirm'
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal_server'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  before_validation :check_for_existence
  validates :title, presence: {message: " ne dois pas être vide", }
  validates :content, presence: {message: " ne dois pas être vide", }
  belongs_to :user
  mount_uploader :image, ImageUploader
  private
  def check_for_existence
    self.attributes.each do |attr|
      return false if self[attr].nil?
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, length: { maximum: 30}
    validates :email, presence: true, length: { maximum: 255},
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
    before_validation {email.downcase!}
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}
    has_many :posts
    def current_user
      session[:user_id]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  # skip_before_action :authenticate_user!
  def not_found
      render status: 404
  end
  
  def unprocessable
      render status: 422
  end
  
  def internal_server 
      render status: 500
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: %i[ show edit update destroy ]
  
  # GET /feeds or /feeds.json
  def index
    @feeds = Feed.all
  end
  
  # GET /feeds/1 or /feeds/1.json
  def show
  end
  
  # GET /feeds/new
  def new
    @feed = Feed.new
  end
  
  # GET /feeds/1/edit
  def edit
  end
  
  # POST /feeds or /feeds.json
  def create
    @feed = Feed.new(feed_params)
    
    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: "Feed was successfully created." }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1 or /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: "Feed was successfully updated." }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1 or /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: "Feed was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def feed_params
      params.require(:feed).permit(:image, :image_cache)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
# coding: utf-8
class PostsController < ApplicationController
  before_action :find_id, only: %i[show edit update destroy confirmed confirm]
  def index
    @posts = Post.where(publish:true)
  end
  
  def create
    post = Post.new(post_params)
    post.user_id = session[:user_id]
    post.update(publish:false)
    if post.valid?
      post.save
      redirect_to confirm_path(post.id)
    else
      @post = post
      render :new
    end
  end
  
  def new
    @post = Post.new
  end
  
  def edit
  end
  
  def show
  end
  
  def update
    if @post.update(post_params)
      redirect_to confirm_path(@post.id), notice: "Mis a jour réussi"
    else
      render :edit
    end
  end
  
  def destroy
    @post.destroy
    redirect_to posts_path, notice:"J'ai supprimé le post !"
  end
  
  def confirm
  end
  
  def confirmed
    @post.update(publish:true)
    redirect_to posts_path, notice: "Post publier"
  end
  
  private
  def post_params
    params.require(:post).permit(:title, :content, :image, :image_cache)
  end
  def find_id
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to posts_path
    else
      flash[:danger] = "Login Failed"
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = "Deconnecté"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path
    else
      render :new
    end
  end
  def show
    @user = User.find(params[:id])
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
  <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.image %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @feed.image.url, :size => "500x300" %>
</p>
<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/homes/index.html.erb
<style>
  :root {
      --white: #e9e9e9!important;
      --gray: #333!important;
      --blue: #0367a6!important;
      --lightblue: #008997!important;
  }
</style>
<div class="container-fluid text-white" >
  <div class="text-center fs-1" style="font-family: 'ZCOOL KuaiLe';">Welcome to <span style="color: #007693;">FacebookClone</span></div>
  <div class="text-center fs-6" style="font-family: 'ZCOOL KuaiLe', cursive;">Made By Rails</div>
  <div class="d-grid gap-2 col-6 mx-auto" style="margin-top: 150px;">
    <a class="btn text-white" href="<%=new_session_path%>" style="background-color: #007693;">Se Connecter</a>
    <div class="text-center fs-4" style="color: #007693;">
      ou
    </div>
    <a class="btn text-white" href="<%= new_user_path %>" style="background-color: #007693;">S'inscrire</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=ZCOOL+KuaiLe&display=swap" rel="stylesheet">
  </head>
<style>
</style>
  <body>
  <div id='alert'><%= alert %></div>
    <%= yield %>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
</html>

app/views/posts/_form.html.erb
<div class="container">
  <%= form_for @post do |post| %>
    <% if @post.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <% @post.errors.full_messages.each do |msg| %>
          <%= msg %>
        <% end %>
      </div>
    <% end %>

    <div class="form-group">
      <label>Titre</label>
      <%= post.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Contenu</label>
      <%= post.text_area :content, class: "form-control" %>
    </div>

     <div class="field">
        <%= post.label :image %>
      <%= post.file_field :image %>
      </div>

    <div class="form-group">
      <button type="submit" class="btn btn-primary mt-5">Enregistrer</button>
    </div>
    
  <% end %>
</div>

app/views/posts/confirm.html.erb
<div class="container">
  <article class="blog-post pb-5 pt-5">
    <h3>Title: <%= @post.title %></h3>
    <p class="ms-5 mt-5"><%= @post.content %></p>
  </article>
  
  <p>
    <% if @post.image.present? %>
    <strong>Image:</strong>
    <div class="card" style="width: 30rem;">
      <%= image_tag @post.image.url, :class => "card-img-top" %>
    </div>
    <% end %>
    
  <p>
    <a href="<%= edit_post_path(@post.id) %>" class="btn btn-warning me-4">Back to create</a>
    <a href="<%= confirmed_path(@post.id) %>" class="btn btn-success">Je confirme</a>
  </p>
  </p>
</div>

app/views/posts/edit.html.erb
<div class="container">
    <h1>Editer</h1>
    <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="container">
  
  <div class="fs-2 text-center"><div class="text-center fs-1" style="font-family: 'ZCOOL KuaiLe', cursive;">Welcome to <span style="color: #007693;">FacebookClone</span></div></div>
  
  <div class="text-center">Bienvenue <span style="background-color: #007693; font-family: 'ZCOOL KuaiLe', cursive;"><%= current_user.name %></span></div>
  
  <div class="text-center"><%= link_to "Logout", session_path(current_user.id), method: :DELETE, class: "btn btn-danger mt-2"%></div>

</div>





<div class="container" style="margin-bottom: 100px;">

  <p class="text-center text-warning"><%= notice %> </p>

  <div class="d-grid gap-2 col-6 mx-auto mt-5"><a class="btn btn-outline-success" href="<%= new_post_path%>">New tweet</a></div>

</div>

<% @posts.each do |post| %>
  <div class="container mb-5">
    <div class="d-flex justify-content-center align-items-center">
      <div>
          <h5>Title: <%=post.title%><span class="fs-6 ms-3"> by: <%= post.user.name if post.user_id.present? %></span> </h5>
          <div class="card" style="width: 30rem;">
            <% if post.image.present? %>
            <%= image_tag post.image.url, :class => "card-img-top" %>
            <% end %>
            <div class="card-body">
              <p class="card-text"><%= post.content%></p>
            </div>
            <div class="d-flex justify-content-between">
              <% if session[:user_id] == post.user_id %>
                <a href="<%=edit_post_path(post.id)%>" class="btn btn-outline-info btn-sm">Modifier</a>
                <a href="<%=post_path(post.id)%>" class="btn btn-outline-info btn-sm">Voir plus</a>
                <a href="<%= post_path(post.id)%>" class="btn btn-outline-danger btn-sm" data-confirm="Etes de vous sur ?" data-method="DELETE">Supprimer</a>
              <% end %>
            </div>
          </div>
      </div>
    </div>
  </div>
<%end%>

app/views/posts/new.html.erb
<div class="container">
  <h1>Creer un nouveau tweet</h1>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <article class="blog-post pb-5 pt-5">
    <h3>Title: <%= @post.title %></h3>
    <p class="ms-5 mt-5"><%= @post.content %></p>
  </article>
  <p>
    <strong>Image:</strong>
    <div style="width: 30rem">
        <%= image_tag @post.image.url, :class => "card-img-top" %>
    </div>
  </p>
  <p>
    <a href="<%=posts_path%>" class="btn btn-primary">Back</a>
  </p>
</div>

app/views/users/new.html.erb
<div class="container mt-5">
  <div class="text-center">
    <span class="fs-3 px-5 py-3" style="background-color: #007693; font-family: 'ZCOOL KuaiLe', cursive;"> S'inscrire</span>
  </div>
</div>
<div class="container mx-auto">
  <div class="row mt-5">
    
    <%= form_with model: @user, url: users_path do |t| %>
      <div class="row mb-5">
        <%= t.label :name, class: "col-md-4" %>
        <%= t.text_field :name, class: "col-md-4"%>
      </div>

      <div class="row mb-5">
        <%= t.label :email, class: "col-md-4"%>
        <%= t.email_field :email, class: "col-md-4"%>
      </div>

      <div class="row mb-5">
        <%= t.label :password, class: "col-md-4"%>
        <%= t.password_field :password, class: "col-md-4"%>
      </div>

      <div class="row">
        <%= t.label :password_confirmation, class: "col-md-4"%>
        <%= t.password_field :password_confirmation, class: "col-md-4"%>
      </div>

      <div class="text-center mt-5">
        <%= t.submit "Je m'inscris", class: "btn btn-success"%>
      </div>
      <div class="text-center mt-3">
        <a class="fs-6 px-3 py-1 btn" href="<%=new_session_path%>" style="background-color: #007693; font-family: 'ZCOOL KuaiLe', cursive;">J'ai deja un compte</a>
      </div>
  <% end%>
</div>

app/views/users/show.html.erb
<div class="container d-flex justify-content-between">
  <div class="fs-2 text-center">
    Bienvenue <span style="background-color: #007693; font-family: 'ZCOOL KuaiLe', cursive;"><%=@user.name%></span>
  </div>
  <%= link_to "Logout", session_path(current_user.id), method: :DELETE, class: "btn btn-danger mt-2"%>
</div>